package com.server.user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.server.user.entity.OauthUser;
import com.server.user.entity.OauthUserExample;

public interface OauthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    long countByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    int deleteByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    int insert(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    int insertSelective(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    List<OauthUser> selectByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") OauthUser record, @Param("example") OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_user
     *
     * @mbg.generated Mon May 14 13:39:00 CST 2018
     */
    int updateByExample(@Param("record") OauthUser record, @Param("example") OauthUserExample example);
}